### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by tx3jun** [AnSwErYWJ/AudioResamplerate#1]
wooya@wooya-pc:/work/audiotest/AudioResamplerate-2.1$ ls -l
total 32
drwxr-xr-x 2 wooya f403tech 4096 Feb 23 16:49 audio
-rw-r--r-- 1 wooya f403tech  247 Feb 23 16:49 config.ini
-rw-r--r-- 1 wooya f403tech   59 Feb 23 16:49 configure.sh
drwxr-xr-x 2 wooya f403tech 4096 Feb 23 16:49 include
drwxr-xr-x 2 wooya f403tech 4096 Feb 23 17:25 lib
-rw-r--r-- 1 wooya f403tech 1843 Feb 23 16:49 Makefile
-rw-r--r-- 1 wooya f403tech 2541 Feb 23 16:49 README.md
drwxr-xr-x 2 wooya f403tech 4096 Feb 23 16:50 source
wooya@wooya-pc:/work/audiotest/AudioResamplerate-2.1$ make
gcc -Wall -O2 -Llib -liniparser -llog -lresamplerate -I./include/ source/resamplerate.o source/iniparser.o source/dictionary.o source/log.o source/samplerate.o source/src_sinc.o source/src_zoh.o source/src_linear.o -o bin/resamplerate
/usr/bin/ld: cannot open output file bin/resamplerate: No such file or directory
collect2: ld returned 1 exit status
make: *** [bin/resamplerate] Error 1
wooya@wooya-pc:/work/audiotest/AudioResamplerate-2.1$

**Comment by AnSwErYWJ** [comment]
Thanks for your issue. 
Now, i have fixed the bug, please update your code. 
Please see this commit 7aea1ba0622dac3198437f0c2bdfef10ff4ebac8.
