### ISSUE TITLE
how to change from 16bit to 8bit

### ISSUE THREAD

**Issue by tx3jun** [AnSwErYWJ/AudioResamplerate#3]
how to change from 16bit to 8bit

**Comment by AnSwErYWJ** [comment]
AudioResamplerate is used to resample audio, not to change sampling bit. I think changing sampling bit may be a bit complicated.

**Comment by AnSwErYWJ** [comment]
AudioResamplerate is used to resample audio, not to change sampling bit. I think changing sampling bit may be a bit complicated.
