### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [AnSwErYWJ/AudioResamplerate#5]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Audio resampling section](https://github.com/forart/HyMPS/blob/main/AudioRES.md)), can you please set licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate/?label=LICENSE)

...maybe is a GH setup issue ?

Thanks in advance.

**Comment by AnSwErYWJ** [comment]
https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate?label=

**Comment by AnSwErYWJ** [comment]
![](https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate?label=)

**Comment by AnSwErYWJ** [comment]
![](https://flat.badgen.net/github/last-commit/winlinvip/go-aresample?label=)

**Comment by MarcoRavich** [comment]
Yes, we noticed the project is deadlocked, anyway it could be useful to understand how the code could be usable.

Thanks anyway.

**Comment by AnSwErYWJ** [comment]
@forart , hi.

I just added a license to this project, but I don’t know why the icon is not displayed: ![](https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate?label=)
(generate string: https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate?label=)

I tried other projects and it's ok, I guess there may be a delay.

Maybe it can be expressed in words：BSD-2-Clause License.

Attach last commit by the way：![](https://flat.badgen.net/github/last-commit/AnSwErYWJ/AudioResamplerate?label=)
(generate string: https://flat.badgen.net/github/last-commit/AnSwErYWJ/AudioResamplerate?label=)

Thanks anyway.

**Comment by AnSwErYWJ** [comment]
@forart , hi.

I just added a license to this project, but I don’t know why the icon is not displayed.(generate string: https://flat.badgen.net/github/license/AnSwErYWJ/AudioResamplerate?label=)

I tried other projects and it's ok, I guess there may be a delay.

Maybe it can be expressed in words：BSD-2-Clause License.

Attach last commit by the way：![](https://flat.badgen.net/github/last-commit/AnSwErYWJ/AudioResamplerate?label=)
(generate string: https://flat.badgen.net/github/last-commit/AnSwErYWJ/AudioResamplerate?label=)

Thanks anyway.

**Comment by MarcoRavich** [comment]
Yes, if you check out page(s), we adopted those two badges:

https://github.com/forart/HyMPS/blob/main/AudioRES.md

Anyway the badges doesn't update in realtime, so the license one will change later.

Thanks

**Comment by MarcoRavich** [comment]
Works now, thanks !
